config/routes.rb
Rails.application.routes.draw do


  resources :produits
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"

   get 'details', to: 'home#details_produit'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/produit.rb
class Produit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end

    def details_produit
        @produit = params[:produitId]
        #redirect_to root_path()
     end
    
end

app/controllers/produits_controller.rb
class ProduitsController < ApplicationController
  before_action :set_produit, only: %i[ show edit update destroy ]

  # GET /produits or /produits.json
  def index
    @produits = Produit.all
  end

  # GET /produits/1 or /produits/1.json
  def show
  end

  # GET /produits/new
  def new
    @produit = Produit.new
  end

  # GET /produits/1/edit
  def edit
  end

  # POST /produits or /produits.json
  def create
    @produit = Produit.new(produit_params)

    respond_to do |format|
      if @produit.save
        format.html { redirect_to produit_url(@produit), notice: "Produit was successfully created." }
        format.json { render :show, status: :created, location: @produit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produits/1 or /produits/1.json
  def update
    respond_to do |format|
      if @produit.update(produit_params)
        format.html { redirect_to produit_url(@produit), notice: "Produit was successfully updated." }
        format.json { render :show, status: :ok, location: @produit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produits/1 or /produits/1.json
  def destroy
    @produit.destroy

    respond_to do |format|
      format.html { redirect_to produits_url, notice: "Produit was successfully destroyed." }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produit
      @produit = Produit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produit_params
      params.require(:produit).permit(:nom, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produits_helper.rb
module ProduitsHelper
end

app/views/home/details_produit.html.erb
<h5>page détails produit</h5>

<h6> index du produit </h6>
<%= @produit %>
<br>    

<% if Produit.where(id: @produit).present? %>
    le produit existe dans la bdd
<% else %>
    le produit n'existe pas dans la bdd
<% end %>

<hr>

<%= link_to "home", root_path %>

app/views/home/index.html.erb
<h5>   home index </h5>
<button type="button" onclick="ScanQr()">Scanner QR code</button>

<hr>       

<span> Index produit trouvé </span>
<span id="qr-result-index"> </span>

<%# appel du controlelr js scanqr %>
<div data-controller="scanqr">
  <input id="qr-result-input" data-scanqr-target="name" type="text">

</div>


<hr>

<%= link_to "home", root_path %>

<hr>

<%= link_to "path with param id", details_path(produitId: 1 ) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apptest3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/produits/_form.html.erb
<%= form_with(model: produit) do |form| %>
  <% if produit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produit.errors.count, "error") %> prohibited this produit from being saved:</h2>

      <ul>
        <% produit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nom, style: "display: block" %>
    <%= form.text_field :nom %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/produits/_produit.html.erb
<div id="<%= dom_id produit %>">
  <p>
    <strong>Nom:</strong>
    <%= produit.nom %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= produit.description %>
  </p>

</div>

app/views/produits/edit.html.erb
<h1>Editing produit</h1>

<%= render "form", produit: @produit %>

<br>

<div>
  <%= link_to "Show this produit", @produit %> |
  <%= link_to "Back to produits", produits_path %>
</div>

app/views/produits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produits</h1>

<div id="produits">
  <% @produits.each do |produit| %>
    <%= render produit %>
    <p>
      <%= link_to "Show this produit", produit %>
    </p>
  <% end %>
</div>

<%= link_to "New produit", new_produit_path %>

app/views/produits/new.html.erb
<h1>New produit</h1>

<%= render "form", produit: @produit %>

<br>

<div>
  <%= link_to "Back to produits", produits_path %>
</div>

app/views/produits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produit %>

<div>
  <%= link_to "Edit this produit", edit_produit_path(@produit) %> |
  <%= link_to "Back to produits", produits_path %>

  <%= button_to "Destroy this produit", @produit, method: :delete %>
</div>